// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC79TQrbx3Gw-9sOHLPBb6gkYQNa_Tp-Ls',
    appId: '1:259502166626:web:e1b282041906a7f707773b',
    messagingSenderId: '259502166626',
    projectId: 'inclusiveconnect-b47e2',
    authDomain: 'inclusiveconnect-b47e2.firebaseapp.com',
    storageBucket: 'inclusiveconnect-b47e2.firebasestorage.app',
    measurementId: 'G-HQJLLHRCLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWxlLrwPPjFw_jt5shCZWDGVjVyTmiOYo',
    appId: '1:259502166626:android:47b7e91c7a58ad6307773b',
    messagingSenderId: '259502166626',
    projectId: 'inclusiveconnect-b47e2',
    storageBucket: 'inclusiveconnect-b47e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaMmSuk85ugDFWRDsUCE2-Qv_iLNvcE2Y',
    appId: '1:259502166626:ios:3b62684647e5f5ba07773b',
    messagingSenderId: '259502166626',
    projectId: 'inclusiveconnect-b47e2',
    storageBucket: 'inclusiveconnect-b47e2.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppAgyFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaMmSuk85ugDFWRDsUCE2-Qv_iLNvcE2Y',
    appId: '1:259502166626:ios:3b62684647e5f5ba07773b',
    messagingSenderId: '259502166626',
    projectId: 'inclusiveconnect-b47e2',
    storageBucket: 'inclusiveconnect-b47e2.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppAgyFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC79TQrbx3Gw-9sOHLPBb6gkYQNa_Tp-Ls',
    appId: '1:259502166626:web:605b107200da9f4407773b',
    messagingSenderId: '259502166626',
    projectId: 'inclusiveconnect-b47e2',
    authDomain: 'inclusiveconnect-b47e2.firebaseapp.com',
    storageBucket: 'inclusiveconnect-b47e2.firebasestorage.app',
    measurementId: 'G-8FC0WFZTBC',
  );

}